[package]
name = "eyesemoji"
version = "0.1.0"
authors = ["liclac <hi@liclac.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12"
blurz = "0.4"
blurmock = "0.1"
